// Banco de dados de nutrientes por ingrediente
// Valores por 100g (aproximados - baseado em USDA)
// CORRIGIDO: Valores realistas para evitar exorbitância

export const mealNutritionDatabase: Record<string, {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  vitamins: Record<string, string>;
  minerals: Record<string, string>;
}> = {
  // Proteínas
  'Chicken': {
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    vitamins: { 'B6': '0.9', 'B12': '0.3', 'Niacina': '9.2' },
    minerals: { 'Selênio': '22', 'Fósforo': '200', 'Potássio': '256' },
  },
  'Beef': {
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    vitamins: { 'B12': '2.4', 'B6': '0.9', 'Niacina': '6.3' },
    minerals: { 'Ferro': '2.6', 'Zinco': '6.3', 'Fósforo': '195' },
  },
  'Pork': {
    calories: 242,
    protein: 27,
    carbs: 0,
    fat: 14,
    fiber: 0,
    vitamins: { 'Tiamina': '0.9', 'B6': '0.9', 'B12': '0.7' },
    minerals: { 'Zinco': '2.5', 'Selênio': '36', 'Fósforo': '201' },
  },
  'Fish': {
    calories: 96,
    protein: 22,
    carbs: 0,
    fat: 1.1,
    fiber: 0,
    vitamins: { 'D': '570', 'B12': '3.2', 'Niacina': '8.9' },
    minerals: { 'Selênio': '36', 'Iodo': '93', 'Fósforo': '210' },
  },
  'Salmon': {
    calories: 206,
    protein: 22,
    carbs: 0,
    fat: 13,
    fiber: 0,
    vitamins: { 'D': '449', 'B12': '3.2', 'Omega-3': '2300' },
    minerals: { 'Selênio': '36', 'Potássio': '628', 'Fósforo': '252' },
  },
  'Shrimp': {
    calories: 99,
    protein: 24,
    carbs: 0,
    fat: 0.3,
    fiber: 0,
    vitamins: { 'B12': '1.7', 'Astaxantina': '5', 'Selênio': '38' },
    minerals: { 'Cobre': '0.3', 'Zinco': '1.5', 'Iodo': '35' },
  },

  // Carboidratos
  'Rice': {
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    vitamins: { 'B1': '0.07', 'B3': '1.5', 'B6': '0.15' },
    minerals: { 'Manganês': '0.6', 'Fósforo': '68', 'Magnésio': '19' },
  },
  'Pasta': {
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.1,
    fiber: 3,
    vitamins: { 'Folato': '93', 'Tiamina': '0.6', 'Niacina': '4.7' },
    minerals: { 'Ferro': '1.8', 'Manganês': '1.0', 'Fósforo': '189' },
  },
  'Bread': {
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.3,
    fiber: 2.7,
    vitamins: { 'Folato': '67', 'Tiamina': '0.24', 'Niacina': '3.2' },
    minerals: { 'Ferro': '2.7', 'Magnésio': '22', 'Manganês': '0.6' },
  },
  'Potato': {
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.1,
    vitamins: { 'C': '8', 'B6': '0.3', 'Ácido Fólico': '19' },
    minerals: { 'Potássio': '421', 'Manganês': '0.12', 'Fósforo': '57' },
  },

  // Vegetais
  'Tomato': {
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    vitamins: { 'C': '14', 'K': '7.9', 'A': '833' },
    minerals: { 'Potássio': '237', 'Manganês': '0.12', 'Magnésio': '11' },
  },
  'Onion': {
    calories: 40,
    protein: 1.1,
    carbs: 9,
    fat: 0.1,
    fiber: 1.7,
    vitamins: { 'C': '7.4', 'Folato': '19', 'B6': '0.12' },
    minerals: { 'Potássio': '146', 'Manganês': '0.17', 'Cálcio': '23' },
  },
  'Garlic': {
    calories: 31,
    protein: 0.6,
    carbs: 7,
    fat: 0.5,
    fiber: 0.5,
    vitamins: { 'C': '31', 'B6': '1.2', 'Alicina': '5' },
    minerals: { 'Manganês': '1.7', 'Selênio': '14.2', 'Cálcio': '181' },
  },
  'Carrot': {
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    vitamins: { 'A': '961', 'K': '13.2', 'C': '3.6' },
    minerals: { 'Potássio': '320', 'Manganês': '0.14', 'Magnésio': '12' },
  },
  'Broccoli': {
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.4,
    vitamins: { 'C': '89', 'K': '101.6', 'Folato': '63' },
    minerals: { 'Cálcio': '47', 'Ferro': '0.7', 'Manganês': '0.21' },
  },
  'Spinach': {
    calories: 23,
    protein: 2.7,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    vitamins: { 'K': '482.9', 'A': '469', 'Folato': '58' },
    minerals: { 'Ferro': '2.7', 'Cálcio': '99', 'Magnésio': '79' },
  },
  'Lettuce': {
    calories: 15,
    protein: 1.2,
    carbs: 2.9,
    fat: 0.3,
    fiber: 1.3,
    vitamins: { 'K': '102.3', 'A': '370', 'Folato': '38' },
    minerals: { 'Cálcio': '36', 'Ferro': '0.4', 'Magnésio': '13' },
  },
  'Bell Pepper': {
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2,
    vitamins: { 'C': '80', 'A': '3131', 'Folato': '46' },
    minerals: { 'Potássio': '211', 'Manganês': '0.08', 'Magnésio': '12' },
  },
  'Cucumber': {
    calories: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    vitamins: { 'K': '16.4', 'C': '2.8', 'A': '105' },
    minerals: { 'Potássio': '147', 'Magnésio': '13', 'Cálcio': '16' },
  },

  // Laticínios
  'Cheese': {
    calories: 402,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    vitamins: { 'A': '721', 'B12': '1.5', 'K2': '5' },
    minerals: { 'Cálcio': '721', 'Fósforo': '456', 'Zinco': '3.1' },
  },
  'Milk': {
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    vitamins: { 'D': '61', 'A': '185', 'B12': '0.5' },
    minerals: { 'Cálcio': '113', 'Fósforo': '84', 'Potássio': '132' },
  },
  'Eggs': {
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    vitamins: { 'Colina': '147', 'B12': '0.9', 'D': '110' },
    minerals: { 'Selênio': '30.7', 'Ferro': '1.2', 'Fósforo': '172' },
  },
  'Butter': {
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    fiber: 0,
    vitamins: { 'A': '2499', 'E': '2.3', 'K': '7' },
    minerals: { 'Selênio': '1' },
  },

  // Frutas
  'Lemon': {
    calories: 29,
    protein: 1.1,
    carbs: 9,
    fat: 0.3,
    fiber: 2.8,
    vitamins: { 'C': '53', 'Folato': '11', 'B6': '0.08' },
    minerals: { 'Potássio': '138', 'Cálcio': '26', 'Magnésio': '8' },
  },
  'Orange': {
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.3,
    fiber: 2.4,
    vitamins: { 'C': '53.2', 'A': '225', 'Folato': '30' },
    minerals: { 'Potássio': '181', 'Cálcio': '40', 'Magnésio': '10' },
  },
  'Banana': {
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    vitamins: { 'B6': '0.4', 'C': '8.7', 'Folato': '25' },
    minerals: { 'Potássio': '358', 'Manganês': '0.27', 'Magnésio': '27' },
  },
  'Apple': {
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    vitamins: { 'C': '4.6', 'A': '54', 'K': '2.2' },
    minerals: { 'Potássio': '107', 'Manganês': '0.04', 'Cálcio': '6' },
  },
  'Strawberry': {
    calories: 32,
    protein: 0.8,
    carbs: 8,
    fat: 0.3,
    fiber: 2,
    vitamins: { 'C': '58.8', 'Folato': '24', 'K': '2.2' },
    minerals: { 'Potássio': '153', 'Manganês': '0.39', 'Magnésio': '13' },
  },

  // Óleos e Temperos
  'Salt': {
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    vitamins: {},
    minerals: { 'Sódio': '38758' },
  },
  'Oil': {
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    vitamins: { 'E': '14.4', 'K': '60.2' },
    minerals: { 'Ferro': '0.6' },
  },
  'Black Pepper': {
    calories: 251,
    protein: 10,
    carbs: 64,
    fat: 3,
    fiber: 25,
    vitamins: { 'K': '163.7', 'C': '21' },
    minerals: { 'Ferro': '9.7', 'Magnésio': '194', 'Manganês': '12.8' },
  },
  'Oregano': {
    calories: 265,
    protein: 9,
    carbs: 69,
    fat: 4.3,
    fiber: 42,
    vitamins: { 'K': '621.4', 'C': '43.3' },
    minerals: { 'Ferro': '36.3', 'Cálcio': '1597', 'Manganês': '4.99' },
  },
  'Basil': {
    calories: 23,
    protein: 3.2,
    carbs: 2.7,
    fat: 0.6,
    fiber: 1.6,
    vitamins: { 'K': '27.3', 'A': '264', 'C': '18' },
    minerals: { 'Ferro': '3.2', 'Cálcio': '64', 'Manganês': '0.72' },
  },

  // Especiarias
  'Paprika': {
    calories: 282,
    protein: 14,
    carbs: 55,
    fat: 13,
    fiber: 27,
    vitamins: { 'A': '48359', 'C': '80.9', 'E': '29.8' },
    minerals: { 'Ferro': '25.5', 'Magnésio': '196', 'Potássio': '2280' },
  },
  'Cumin': {
    calories: 375,
    protein: 18,
    carbs: 44,
    fat: 22,
    fiber: 11,
    vitamins: { 'C': '21', 'K': '520.2', 'E': '3.97' },
    minerals: { 'Ferro': '66.4', 'Magnésio': '366', 'Manganês': '28.8' },
  },
  'Ginger': {
    calories: 80,
    protein: 1.8,
    carbs: 18,
    fat: 0.8,
    fiber: 2.4,
    vitamins: { 'C': '5', 'B6': '0.16' },
    minerals: { 'Manganês': '0.23', 'Potássio': '415', 'Ferro': '0.6' },
  },

  // Molhos e Condimentos
  'Soy Sauce': {
    calories: 61,
    protein: 8,
    carbs: 5.6,
    fat: 0,
    fiber: 0,
    vitamins: {},
    minerals: { 'Sódio': '5586', 'Ferro': '0.6' },
  },
  'Vinegar': {
    calories: 18,
    protein: 0.04,
    carbs: 0.9,
    fat: 0,
    fiber: 0,
    vitamins: {},
    minerals: { 'Ferro': '0.2', 'Potássio': '24' },
  },
  'Honey': {
    calories: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    fiber: 0.2,
    vitamins: { 'C': '0.5' },
    minerals: { 'Cálcio': '6', 'Ferro': '0.42', 'Magnésio': '2' },
  },
};

/**
 * Obtém nutrientes de um ingrediente
 */
export function getNutritionData(ingredientName: string) {
  return mealNutritionDatabase[ingredientName] || {
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    vitamins: {},
    minerals: {},
  };
}